#!/bin/bash

# Configure this script here:
DEFAULT_CMD=compile
ROOT_DIR="buildroot-2013.11"

# Unused
SSH_IP="141.37.31.27"

#-------Configs------

CONFIG_DIR="../configs"
SAV_BR_CONFIG="$CONFIG_DIR/br.config"
APP_SRC="../app/src"
SCRIPTS_DIR="../scripts"

#--------Script-------

cd $ROOT_DIR

rebuild()
{
        clean
        compile
}

clean()
{
        saveConfigs
        make clean
}

compile()
{
	repack
        loadBR
        make
	copy
}

config()
{
        loadBR
        make menuconfig
        saveBR
}

configBB()
{
        make busybox-menuconfig
        saveBB
}

configK()
{
        make linux-menuconfig
        saveK
}

repack()
{
	rmPack
	pack
}

rmPack()
{
	rm -f dl/jefa_web.tar.gz

	rm -f -r output/build/jefa_web-1.0/
}

pack()
{
        cd ../website
        tar -czf jefa_web.tar.gz src
        cd ../$ROOT_DIR
}

copy()
{
	cp -f output/images/uImage /srv/tftp/rpi/uImage-7
	echo "copied image to tftp"
}

control()
{
	ssh -oBatchMode=yes -oStrictHostKeyChecking=no root@$SSH_IP
}

live()
{
	copy_files
	install_live
}

install()
{
	#install apps
	cd ../app/src
	make install

	#install modules
	cd ../../driver/src
	make install

	#copy scripts
	cd ../../scripts
	cp S98initLED_TAST S97mdev_hotplug ../rootfs_files/etc/init.d/
	cp led.sh ../rootfs_files/usr/share/
	cd ../$ROOT_DIR
}

install_live()
{
	scp -oBatchMode=yes -oStrictHostKeyChecking=no -r ../rootfs_files/* root@$SSH_IP:/
}

download()
{
        make source
}

#---------Config----------

# Configure the right defconfigs!
loadBR()
{
        make defconfig BR2_DEFCONFIG="$SAV_BR_CONFIG"
}

saveConfigs()
{
        saveBR
        saveK
        saveBB
}

saveK()
{
        make linux-update-defconfig
}

saveBB()
{
        make busybox-update-config
}

saveBR()
{
        make savedefconfig
}


if [ $# -eq 0 ]
then
        command=$DEFAULT_CMD
else	
	command=$1
fi

if [ "$(type -t "$command")" == "function" ]
then
        echo "Running $command"

        $command
else
        echo "Unrecognized command." 1>&2
fi
